<!doctype html>
<html lang="en">
<?php include_once '../views/layouts/header.phtml'; ?>
<body>

<?php include_once "../views/articles/menu.phtml"; ?>

<div class="ui two column centered grid">
        <?php include_once "../views/articles/detail/detail-article.phtml"; ?>
</div>

<div class="ui three column grid">
    <div class="column"></div>
    <div class="column">
    <div class="ui comments">
        <h3 class="ui dividing header">Comments</h3>
        <?php if(!empty($comments)): ?>

            <?php foreach ($comments as $comment): ?>

            <div class="comment">
                <a class="avatar">
                    <img src="/images/img_placeholder_avatar.jpg">
                </a>
                <div class="content">
                    <a href="/user/profile?id=<?= $comment['user_id']; ?>" class="author"><?= $comment['first_name'] ?> <?= $comment['last_name']; ?></a>
                    <div class="metadata">
                        <span class="date"><?= $comment['created_at']; ?></span>
                    </div>
                    <div class="text">
                        <?= $comment['text']; ?>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        <?php else: ?>
            No comments yet...
        <?php endif; ?>
        <form class="ui reply form"
              method="post"
              action="/comments/add">
            <div class="field <?= isset($empty) ? 'error' : '' ?>">
                <textarea name="text"></textarea>
            </div>
            <input type="hidden" name="article_id" value="<?= $id; ?>">
            <button type="submit" class="ui blue labeled submit icon button">
                <i class="icon edit"></i> Add Reply
            </button>
        </form>
    </div>
    </div>
</div>

</body>
</html>