<!doctype html>
<html lang="en">
<?php
include_once '../views/layouts/header.phtml'
?>
<body>

<?php
include_once '../views/banned/menu.phtml';
?>

<div class="ui three column centered grid" style="margin-top: 120px">
    <div class="ui negative message column">
        <div class="header">
            Banned
        </div>
        <p>
            Sorry, your account, for some reason, was banned by administration
        </p>
    </div>
</div>

</body>
</html>