<form action="/articles/edit/action"
      method="post"
      class="ui form <?= isset($empty) ? 'error' : ''; ?>"
      style="margin-top: 40px">

    <h3 class="ui dividing header">Edit article</h3>

    <div class="ui error message">
        <div class="header">We had some issues</div>
        <p>Please fulfill all fields</p>
    </div>

    <div class="field">
        <input type="hidden"
               name="id"
               value="<?= $article['id']; ?>">
    </div>

    <div class="field">
        <label for="name">Article Name</label>
        <input type="text"
               name="name"
               id="name"
               value="<?= $article['name']; ?>"
               placeholder="Your article">
    </div>

    <div class="field">
        <label for="text">Article</label>
        <textarea id="text"
                  name="text"
                  rows="6"
        ><?= $article['text'] ?></textarea>
    </div>

    <div class="field">
        <label for="categories">Category</label>
        <select id="categories" name="category_id">
            <?php foreach ($categories as $category): ?>
                <option value="<?= $category['id']; ?>"><?= ucfirst($category['name']); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <button type="submit" class="ui button green">Edit</button>
</form>