<!doctype html>
<html lang="en">
<?php include_once '../views/layouts/header.phtml'; ?>
<body>

<?php include_once "../views/articles/menu.phtml"; ?>

<div class="ui two column centered grid">
    <div class="row">
        <div>
            <p class="headers">Login: <?= $user['login']; ?></p>
        </div>
        <div>
            <p class="headers">Full name: <?= $user['first_name']; ?> <?= $user['last_name']; ?></p>
        </div>
        <div>
            <p class="headers">Login: <?= $user['login']; ?></p>
        </div>
        <div>
            <p class="headers">Login: <?= $user['login']; ?></p>
        </div>
    </div>

    <p class="headers">Full name: </p>
</div>

</body>
</html>