<!doctype html>
<html lang="en">
<?php include_once '../views/layouts/header.phtml'; ?>
<body>

<?php include_once "../views/articles/menu.phtml"; ?>

<div class="ui grid">
    <div class="four wide column"></div>
    <div class="eight wide column">
        <p>Login: <?= $user['login']; ?></p>

        <p>Full name: <?= $user['first_name']; ?> <?= $user['last_name']; ?></p>

        <p>Email: <?= $user['email']; ?></p>

        <p>User created: <?= (new DateTime($user['created_at']))->format('jS F Y'); ?></p>

        <p>Total articles: <?= $user['articles_cnt']; ?></p>

        <p>Total comments: <?= $user['comments_cnt']; ?></p>
        <?php if(in_array($auth_user['user_type_id'], UserTypes::ADMINISTRATION)): ?>
            <p >Admin actions:
                <?php if($user['user_type_id'] != UserTypes::TYPE_ADMIN && $user['banned'] == Users::USER_NOT_BANNED): ?>
                    <a href="/admin/block/add?user_id=<?= $user['id']; ?>&profile" title="Block user">
                        <i class="ban red icon"></i>
                    </a>
                <?php elseif($user['banned'] == Users::USER_IS_BANNED): ?>
                    <a href="/admin/block/remove?user_id=<?= $user['id']; ?>&profile" title="Unblock user">
                        <i class="unlock green icon"></i>
                    </a>
                <?php endif; ?>
            </p>

            <?php if($user['comments_cnt'] > 0): ?>
                <div class="ui list">
                    <p>User comments:</p>
                    <?php foreach ($user['comments'] as $comment): ?>
                        <div class="item">
                            <div class="content">
                                <p class="header"><?= $comment['text']; ?></p>
                                <div class="description"><?= (new DateTime($user['created_at']))->format('jS F Y'); ?></div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if($user['articles_cnt'] > 0): ?>
                <div class="ui list">
                    <p>User articles:</p>
                    <?php foreach ($user['articles'] as $article): ?>
                        <div class="item">
                            <div class="content">
                                <p class="header"><?= $article['name']; ?></p>
                                <div class="description"><?= (new DateTime($user['created_at']))->format('jS F Y'); ?></div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div class="four wide column"></div>
</div>


</body>
</html>