<!doctype html>
<html lang="en">
<?php include_once '../views/layouts/header.phtml'; ?>
<body>

<?php include_once "../views/articles/menu.phtml"; ?>

<div>
    <h4 class="ui header">Login: <?= $user['login']; ?></h4>

    <h4 class="headers">Full name: <?= $user['first_name']; ?> <?= $user['last_name']; ?></h4>

    <h4 class="headers">Email: <?= $user['email']; ?></h4>

    <h4 class="headers">User created: <?= (new DateTime($user['created_at']))->format('jS F Y'); ?></h4>

    <h4 class="headers">Total articles: <?= $user['articles_cnt']; ?></h4>

    <h4 class="headers">Total comments: <?= $user['comments_cnt']; ?></h4>
        <?php if(in_array($auth_user['user_type_id'], UserTypes::ADMINISTRATION)): ?>
            <h4 class="headers">Admin actions:
                <?php if($user['user_type_id'] != UserTypes::TYPE_ADMIN && $user['banned'] == Users::USER_NOT_BANNED): ?>
                    <a href="/admin/block/add?user_id=<?= $user['id']; ?>" title="Block user">
                        <i class="ban red icon"></i>
                    </a>
                <?php elseif($user['banned'] == Users::USER_IS_BANNED): ?>
                    <a href="/admin/block/remove?user_id=<?= $user['id']; ?>" title="Unblock user">
                        <i class="unlock green icon"></i>
                    </a>
                <?php endif; ?>
            </h4>


            <div class="ui list">
                <h4 class="headers">User comments:</h4>
                <?php foreach ($user['comments'] as $comment): ?>
                <div class="item">
                    <div class="content">
                        <p class="header"><?= $comment['text']; ?></p>
                        <div class="description"><?= (new DateTime($user['created_at']))->format('jS F Y'); ?></div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

            <div class="ui list">
                <h4 class="headers">User articles:</h4>
                <?php foreach ($user['articles'] as $article): ?>
                    <div class="item">
                        <div class="content">
                            <p class="header"><?= $article['name']; ?></p>
                            <div class="description"><?= (new DateTime($user['created_at']))->format('jS F Y'); ?></div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
    <?php endif; ?>
</div>

</body>
</html>