<!doctype html>
<html lang="en">
<?php
 include_once "../views/layouts/header.phtml";
?>
<body>

<div class="ui three column centered grid" style="margin-top: 120px">
    <div class="ui negative message column">
        <div class="header">
            404 Not Found
        </div>
        <p>
            Sorry, an error has occured, Requested page not found!
        </p>
        <a href="/articles">
            To Articles List
        </a>
    </div>
</div>

</body>
</html>