<!doctype html>
<html lang="en">

<?php
    include_once '../views/layouts/header.phtml';

    $is_field_empty = false;

    if (isset($_REQUEST['empty'])) {
        $is_field_empty = true;
    }
?>

<body>
    <div class="ui three column centered grid">
        <div class="column">
            <form action="/article/save"
                  method="post"
                  class="ui form <?= $is_field_empty ? 'error' : ''; ?>"
                  style="margin-top: 40px">

                <h3 class="ui dividing header">Edit article</h3>

                <div class="ui error message">
                    <div class="header">We had some issues</div>
                        <p>Please fulfill all fields</p>
                </div>

                <div style="display: none">
                    <input type="hidden"
                           name="id"
                           value="<?= $article['id']; ?>">
                </div>

                <div class="field">
                    <label for="article_name">Article Name</label>
                    <input type="text"
                           name="article_name"
                           id="article_name"
                           placeholder="Your article"
                           value="<?= $article['article_name']; ?>">
                </div>

                <div class="field">
                    <label for="article">Article</label>
                    <textarea id="article"
                              name="article"
                              rows="3"
                    ><?= $article['article']; ?></textarea>
                </div>

                <div class="field">
                    <label for="categories">Category</label>
                    <select id="categories" name="category_id">
                        <?php foreach ($categories as $key => $category): ?>
                            <option value="<?= $key; ?>"
                                <?php if($article['category_id'] == $key) echo 'selected' ?>>
                                <?= $category; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <button type="submit" class="ui button green">Save</button>
            </form>
        </div>
    </div>

</body>
</html>