<!doctype html>
<html lang="en">

<?php
    include_once '../views/layouts/header.phtml';
?>

    <body>
        <div class="ui three column centered grid">
            <div class="column">
                <?php
                $is_field_empty = false;

                if (isset($_REQUEST['empty'])) {
                    $is_field_empty = true;
                }

                include_once '../views/form.phtml';
                ?>


                <?php if(empty(!$all_articles[0])): ?>
                    <a href="/articles" style="margin-top: 20px; display: block">To Articles List</a>
                <?php endif; ?>

            </div>
        </div>
    </body>
</html>