<div class="ui divided items">
    <?php foreach ($articles as $key => $article): ?>

        <div class="item">
            <div class="content">
                <p class="header"><?= $article['name']; ?></p>

                <?php if ($article['status'] == Articles::STATUS_DRAFT): ?>
                    <label class="ui grey right ribbon label">Draft</label>
                <?php elseif ($article['status'] == Articles::STATUS_REMOVED): ?>
                    <label class="ui red right ribbon label">Removed</label>
                <?php endif; ?>

                <div class="meta">
                    <span><?= ucfirst($article['category_name']); ?></span>
                </div>
                <div class="description">
                    <p>
                        <?= $article['text']; ?>
                    </p>
                </div>
                <?php if (isset($edit_on)): ?>
                    <?php if ($article['status'] == Articles::STATUS_ACTIVE): ?>
                        <div class="extra content">
                            <a href="/articles/edit?id=<?= $article['id']; ?>"
                               class="ui basic blue button">
                                Edit
                            </a>
                            <a href="/articles/remove?id=<?= $article['id']; ?>"
                               class="ui basic red button">
                                Delete
                            </a>
                        </div>
                    <?php elseif ($article['status'] == Articles::STATUS_DRAFT): ?>
                        <div class="extra content">
                            <a href="/articles/edit?id=<?= $article['id']; ?>"
                               class="ui basic green button">
                                Add
                            </a>
                            <a href="/articles/edit?id=<?= $article['id']; ?>"
                               class="ui basic blue button">
                                Edit
                            </a>
                            <a href="/articles/remove?id=<?= $article['id']; ?>"
                               class="ui basic red button">
                                Delete
                            </a>
                        </div>
                    <?php elseif ($article['status'] == Articles::STATUS_REMOVED): ?>
                        <div class="extra content">
                            <a href="/articles/edit?id=<?= $article['id']; ?>"
                               class="ui basic green button">
                                Restore
                            </a>
                        </div>
                    <?php endif; ?>
                <?php else: ?>
                    <div class="extra">
                        <a href="/articles/detail?id=<?= $article['id']; ?>">
                            Additional Details
                        </a>

                        <span class="right floated">
                            <a href="/rating/toggle?article_id=<?= $article['id']; ?>">
                                <i class="heart <?= $article['user_has_rated'] ? 'red' : 'outline'  ?> like icon"></i>
                            </a>
                            <?= $article['rating_cnt'] ?>
                            likes
                        </span>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>

    <a href="/articles/add" class="ui left floated button green" style="margin-top: 15px"> Add new Article</a>
</div>