<!doctype html>
<html lang="en">
<?php include_once '../views/layouts/header.phtml'; ?>
<body>

<?php include_once "../views/articles/menu.phtml"; ?>

<div id="app"></div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>
<script src="/dist/bundle.js"></script>
</body>
</html>