<div class="ui secondary pointing menu">
    <a class="<?= isset($location) && $location === 'all' ? 'active' : '' ?> item" href="/articles">
        Home
    </a>
    <a class="<?= isset($location) && $location === 'user' ? 'active' : '' ?> item" href="/articles/user-articles">
        My Articles
    </a>
    <div class="right menu">
        <a href="/user/logout"
           class="ui item">
            Logout
        </a>
    </div>
</div>