<div class="ui secondary pointing menu">
    <a class="<?= isset($location) && $location === 'all' ? 'active' : '' ?> item" href="/articles">
        Home
    </a>
    <a class="<?= isset($location) && $location === 'user' ? 'active' : '' ?> item" href="/articles/user/all">
        My Articles
    </a>
    <?php if(in_array($auth_user['user_type_id'], UserTypes::ADMINISTRATION)): ?>
        <a class="<?= isset($location) && $location === 'admin' ? 'active' : '' ?> item" href="/admin/index">
            All users
        </a>
    <?php endif; ?>
    <div class="right menu">
        <a href="/user/logout"
           class="ui item">
            Logout
        </a>
    </div>
</div>