<form class="ui form" method="post" action="/user/login">
    <div class="field">
        <label for="login">Your login</label>
        <input type="text"
               id="login"
               name="login"
               placeholder="Your login">
    </div>
    <div class="field">
        <label id="password">Your password</label>
        <input type="text"
               id="password"
               name="password"
               placeholder="Password">
    </div>
    <p>
        Don't have an account? <a href="#">Register</a>
    </p>
    <button class="ui right floated button green" type="submit">Login</button>
</form>